### PR TITLE
Added histogram jupyter notebooks

### PR DESCRIPTION
**Pull request by ordirules**
Added a visual histogram example (jupyter notebook).

### CODE REVIEW

**Comment by ordirules** [comment]
I can also add an example for using a 3D version of the histogram (2D area detector + 1D binning photons). Can do that later when free, just need to clean up code.

**Comment by ordirules** [comment]
sorry for the delay, I've included a 3D histogram example (basically the 2d version but the detector is now a 2d detector)

**Comment by danielballan** [comment]
These look great. Thanks!

**Comment by ordirules** [comment]
thanks!
I just realized I should have pinged @pavoljuhas and @chrisvam. These are jupyter notebooks demonstrating the use of the histogram class (2D and 3D). If you have anything to add let me know!

**Pull request merged**
