### PR TITLE
ENH: updated ROI ipynb added bar ROI's and box ROI's

### PR DESCRIPTION
**Pull request by sameera2004**

### CODE REVIEW

**Comment by ericdill** [comment]
Please remove everything in cell [2] and move the cmap='viridis' to cell [1]

**Comment by ericdill** [comment]
In cell [3]:

- change "specified in coords" to "specified in roi_data"
- Add a comment describing this line:
```
    roi_inds, pixel_list = roi.extract_label_indices(label_array)
```

**Comment by ericdill** [comment]
Am I correct that nothing after cell [4] has been changed?

**Comment by ericdill** [comment]
Looks good, thanks @sameera2004 , only a couple of comments

**Comment by sameera2004** [comment]
Actually I added things after cell [15].  From `Generate Bar ROI`

**Comment by ericdill** [comment]
I see that. Can you move cell [3] down right before cell [16] so that it is with the other box-like ROI stuff?

**Comment by ericdill** [comment]
Can you use a 2x2 subplot to combine cells [17], [19] and [21]?  They are related and it would be very cool to see them combined.  I would put them like this:

```
|----------+----------|
|          |          |
|   [21]   |   [17]   |
|          |          |
|          |          |
|----------+----------|
|          |          |
|   [19]   |          |
|          |          |
|          |          |
|----------+----------|
```

This way it is quite obvious that cell [21] is the intersection of the two groups.

**Comment by sameera2004** [comment]
Ready for review

**Comment by sameera2004** [comment]
Updated the notebook ready for review

**Comment by ericdill** [comment]
@sameera2004 looks good. Can you swap the rectangle roi's and the horizontal roi's in the last plot?

**Comment by ericdill** [comment]
Also, why does the horizontal bars plot have a different color scheme?

**Comment by ericdill** [comment]
Oh, i see now. Can you add the cmap to the horizontal bars plot?

**Comment by sameera2004** [comment]
Updated the ipnb, added the camp to `horizontal_bars` and swap the `rectangle_rois` and `horizontal_bars`

**Comment by sameera2004** [comment]
@ericdill this PR is Ready for review

**Comment by ericdill** [comment]
Awesome, thanks @sameera2004

**Comment by sameera2004** [comment]
Thanks @ericdill

**Pull request merged**
