### PR TITLE
fixed the two time correlation notebook

### PR DESCRIPTION
**Pull request by sameera2004**
Changed the two time correlation notebook after changing the results shape in the skbeam/core/correlation.py  to have (num_rois, len(lag_steps), len(lag_steps))

### CODE REVIEW

**Comment by ericdill** [comment]
@sameera2004 Looks really good. Thanks for your effort on this.  Two comments

1. Can you plot the results from correlating the first half?
2. The formatting in cell [10] is a little off, can you fix that?

**Comment by sameera2004** [comment]
@ericdill I added  a plot to show the results from first half data set and fixed the PR, ready to review

**Comment by ericdill** [comment]
Thanks!

**Comment by sameera2004** [comment]
@ericdill  Thanks

**Pull request merged**
