### PR TITLE
API/WIP: Update scikit-beam-examples to match skxray-> skbeam rename.

### PR DESCRIPTION
**Pull request by ericdill**
@ordirules Can you have a look at the histogram notebooks in this PR? It seems like the 
image plotting might be behaving strangely

### CODE REVIEW

**Comment by ericdill** [comment]
@sameera2004 can you work on updating the xpcs with lmfit notebook? I am getting an error in the third cell.  When that notebook is updated, can you submit a PR against this branch?

**Comment by sameera2004** [comment]
@ericdill sure I will work on XPCS with lmfit and put a PR

**Comment by ordirules** [comment]
I see what you're referring to, the images in histogram3D.ipynb and Histogram2D.ipynb
the images seem to have their aspect ratios set to equal. You can tell because Histogram2D-RingAveraging.ipynb also suffers the problem but since the x and y contain close to the number of pixels the result is not so bad.

I think code like ``ax2.set_aspect('auto')'' should do the trick etc. I would also force a "ax0.set_aspec('equal')" (to be explicit) for the image in Histogram2D-RingAveraging.ipynb since it's an image so equal aspect ratio is more sensible.

Should I make a PR for this or is there a way to edit this PR? (Do I download from your branch and PR to you?)

Also, I figured out how to put a color bar without screwing things up. Instead of calling "cla()" I should really be calling "clf()". The latter will clear the figure and any color bars in the figure while the former does not. (We had an issue where when we ran the code a couple of times with the color bar a new color bar was added every time). Still learning! :-D

**Comment by ericdill** [comment]
Self-merging since this is just a rename PR. @ordirules and @sameera2004 did the heavy lifting of updating code so that the notebooks actually work. Thanks all!

**Pull request merged**
