### PR TITLE
Construct rphi

### PR DESCRIPTION
**Pull request by ordirules**
better example of construct rphi. Use binnedstatistic to transform masked image to polar coordinates. Then use known symmetry (here 10-fold) to fill in the gaps, and use construct_rphi_image to reproject back into an image.

@danielballan this is what i mean. let me know if ok. i have to re-word a little later

### CODE REVIEW

**Comment by danielballan** [comment]
The substance looks good to me. It might be worth cleaning up that pile of blank cells when you come back to re-word.

**Comment by ordirules** [comment]
Done and ready to go, thanks! :-)
The `reconstruct_nfold` code too could maybe also be something in scikit-beam? It's a quick and dirty way to reconstruct an image assuming symmetries. However, I personally think it's better as an example, there are likely more efficient ways to do this.

**Comment by ordirules** [comment]
@danielballan thanks but the actual code in scikit-beam was never merged. I am waiting on @tacaswell to see what he thinks about it.

Here:
https://github.com/scikit-beam/scikit-beam/issues/489

Sorry about the confusion, I should have been clearer about that!
Perhaps we should make a label requesting a member to verify the code in example exists first? It is likely common that new skbeam code + example here are submitted simultaneously.

**Comment by danielballan** [comment]
Ah, sorry. I'm trying to do too many things at once. We could borrow some code from the trackpy docs that executes the notebooks. But there are other things we need to fix about the docs that may be higher priority.

**Pull request merged**
