### PR TITLE
ENH: added notebook for gisaxs 

### PR DESCRIPTION
**Pull request by sameera2004**

### CODE REVIEW

**Comment by sameera2004** [comment]
@ericdill I added notebook for gisaxs https://github.com/scikit-beam/scikit-beam/pull/404

**Comment by ericdill** [comment]
Please use viridis over jet

**Comment by sameera2004** [comment]
Sure I will change the camp

**Comment by sameera2004** [comment]
@ericdill I change the camp ready to review

**Comment by ericdill** [comment]
The axis labels on the images are in pixels. Can you change them to be more appropriate?  Something like degrees for the angles and something like reciprocal angstroms for the q images?

**Comment by sameera2004** [comment]
Sure, they are already in angstroms and degrees, I will change the axis ticks

**Comment by sameera2004** [comment]
@ericdill I added the axis labels, ready for review

**Comment by ericdill** [comment]
What is the meaning of the 'z' value in that plot?

**Comment by sameera2004** [comment]
Ready to review

**Comment by ericdill** [comment]
in the first plot, can you indicate on the axis labels what the units of the angles are? Not sure if this is in degrees or radians

**Comment by sameera2004** [comment]
@ericdill Angles are in radians, fixed the plot, ready for review

**Comment by ericdill** [comment]
Thanks!

**Comment by sameera2004** [comment]
Thanks @ericdill

**Pull request merged**
